insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(1,'One of the Cobol Program division is','Environment Division','Coding division','Specification Division','Editing Division','Environment Division','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(2,'What are the three main types of computer programming languages?','Machine language, assembly language, high level language','Imperative language, functional language, declarative language','COBOL, Fortran-77, C++','A & C','Machine language, assembly language, high level language','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(3,'Every computer has a set of operation code called as .','Data Set','Both','None','Instruction Set','Instruction Set','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(4,'Which of the translator program converts assembly language program into equivalent machine languageprogram?','Compiler','Linker','Assembler','Interpreter','Assembler','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(5,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(6,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(7,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(8,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(9,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(10,'','','','','','','prg');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(11,'Who is the founder of c?','Dennis Rithie','James goshling','Guido van rosuum','Tim berners lee','Dennis Rithie','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(12,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(13,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(14,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(15,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(16,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(17,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(18,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(19,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(20,'','','','','','','c');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(21,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(22,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(23,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(24,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(25,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(26,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(27,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(28,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(29,'','','','','','','java');
insert into question (questionid,question,optiona,optionb,optionc,optiond,answer,category) values(30,'','','','','','','java');
